export const FETCH_ARTICLES = 'ARTICLES/FETCH_ARTICLES';
export const DELETE_ARTICLES = 'ARTICLES/DELETE_ARTICLES';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
